config/routes.rb
Rails.application.routes.draw do

  root 'welcome#home'
  get 'about', to: 'welcome#about'
  resources :testimonials
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
    belongs_to :user
    validates :title, presence: true, length: {minimum: 3, maximum: 50}
    validates :description, presence: true, length: {minimum: 15, maximum: 3000}
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :testimonials, dependent: :destroy
    before_save { self.email = email.downcase }
    validates :username, presence: true, uniqueness: {case_sensitive: false}, length: { minimum: 3, maximum: 25}
    #validates :privelige, presence: true, length: {maximum: 5}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 105 }, uniqueness: { case_sensitive: false },format: { with: VALID_EMAIL_REGEX }
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end
  
end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        flash[:success] = "You have successfully logged in"
        redirect_to user_path(user)
        else
        flash.now[:danger] = "There was something wrong with your login information"
        render 'new'
        end
    end
    def destroy
        session[:user_id] = nil
        flash[:success] = "You have logged out"
        redirect_to root_path
    end
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  
  before_action :set_testimonial, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def index
    @testimonials = Testimonial.paginate(page: params[:page], per_page: 5)
  end
  
  def new
      @testimonial = Testimonial.new
  end
  def create
      #render plain: params{:testimonial}.inspect
      @testimonial = Testimonial.new(testimonial_params)
      @testimonial.user = current_user
      if @testimonial.save
        flash[:success] = "Testimonial was successfully saved/posted"
        redirect_to testimonial_path(@testimonial)
      else
          render 'new'
      end
          
  end
  def show
  end

  def edit
  end
  
  def update
      if @testimonial.update(testimonial_params)
          flash[:success] = "Testimonial was successfully updated"
          redirect_to testimonial_path(@testimonial)
      else
          render 'edit'
      end
  end
  def destroy
     if @testimonial.destroy
         flash[:success] = "Your testimonial was successfully delted"
         redirect_to testimonials_path
     else
         flash[:warning] = "Could not delete testimonial"
         render 'show'
     end
  end
  
  def set_testimonial
    @testimonial = Testimonial.find(params[:id])
  end
  
  def require_same_user
    if current_user != @testimonial.user and !current_user.admin?
      flash[:danger] = "You can only edit or delete your own testimonial"
      redirect_to root_path
    end
  end

  private
    def testimonial_params
      params.require(:testimonial).permit(:title, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]
   def new
       @user = User.new
   end 

   def create
     @user = User.new(user_params)
     if @user.save
       session[:user_id] = @user.id
       flash[:success] = "Welcome to DawaKhana #{@user.username}!"
       redirect_to user_path(@user)
     else
       render 'new'
     end
   end
   def destroy
     @user = User.find(params[:id])
     @user.destroy
     flash[:danger] = "User and all testimonials created by user have been deleted"
     redirect_to users_path
   end
   
  def edit

  end
 
  def update
    if @user.update(user_params)
      flash[:success] = "Your account was updated successfully"
      redirect_to testimonials_path
    else
      render 'edit'
    end
  end
  def show
    @user_testimonials = @user.testimonials.paginate(page: params[:page], per_page: 5)
  end
  
     
  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end
  def set_user
    @user = User.find(params[:id])
  end
  
  def require_same_user
    if current_user != @user and !current_user.admin?
      flash[:danger] = "You can only edit your own account"
      redirect_to root_path
    end
  end
  def require_admin
    if logged_in? and !current_user.admin?
      flash[:danger] = "Only admin users can perform that action"
      redirect_to root_path
    end
  end
  
private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
    redirect_to testimonials_path if logged_in?  
  end
  def about
      
  end
     
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 90})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "img-circle")
  end
end

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
    Copyright © DawaKhana by Raunaq Naidu
    </small>
    <nav>
      <ul>
        <li><%= link_to "About", about_path %></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="container">
    <div class="row">
      <div class="col-xs-10 col-offset-1">
        <% flash.each do |name, msg| %>
          <div class='alert alert-<%="#{name}" %>'>
              <a href="#" class="close" data-dismiss="alert">×</a>
              <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
          </div>
      <% end %>
      </div>
    </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "DawaKhana", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Services", root_path, id: "options"%></li>
        <li><%= link_to "Testimonials", testimonials_path, id: "options"%></li>
        <% if logged_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" id="options">Options <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Write Testimonial", new_testimonial_path %></li>
            <li><%= link_to "View Testimonials", testimonials_path%></li>
            <li><%= link_to "List Patients", users_path %></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Schedule Appointment</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">View Records</a></li>
          </ul>
        </li>
        <% end %>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
        <li><%= link_to current_user.username, user_path(current_user),id: "options" %></li>
        <% end %>
        <% if logged_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" id="options"><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Update profile", edit_user_path(current_user) %></li>
            <li><%= link_to "Write Testimonial", new_testimonial_path %></li>
            <li><%= link_to "View Testimonials",  user_path(current_user)%></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Log out', logout_path, method: :delete %></li>
          </ul>
        </li>
        <% else%>
            <li><%= link_to 'Log in', login_path, id: "options" %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages'%>
  <div class="container">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
          <%= pluralize(obj.errors.count, "error") %>
          prohibited this article from being saved:
          </h2>
          <div class="panel-body">
            <ul>
            <% obj.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/testimonials/_form.html.erb
<%= render 'shared/errors', obj: @testimonial %>
<div class='row'>
  <div class='col-xs-12'>
    <%= form_for(@testimonial, :html => {class: "form-horizontal",role: "form"}) do |f| %>
    <div class="form-group">
      <div class="col-sm-1 control-label">
          <%= f.label :title %>
      </div>
      <div class="col-sm-5">
          <%=f.text_field :title, class: "form-control", placeholder: "Title of testimonial", autofocus: true %>
      </div>

    </div>


    <div class="form-group">
      <div class="col-sm-1 control-label">
          <%= f.label :description %>
      </div>
      <div class="col-sm-10">
          <%= f.text_area :description, class: "form-control", rows: 10, placeholder: "Enter the testimonial here", autofocus: true  %>
      </div>
    </div>


    <div class="form-group">
      <div class="col-sm-offset-5 col-sm-10">
          <%= f.submit class: 'btn btn-primary btn-large' %>
      </div>
    </div>
    <% end %>
    <div align="center" class="col-xs-4 col-xs-offset-4">
    [ <%= link_to "Cancel request", testimonials_path %> ]
    </div>
    
  </div>
</div>

app/views/testimonials/_testimonial.html.erb
<% obj.each do |testimonial| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="testimonial-title">
          <%= link_to testimonial.title, testimonial_path(testimonial) %>
        </div>
        <div class="testimonial-body">
        <%= truncate(testimonial.description, length: 100) %>
        <div class="username">
        <small>~<%= if testimonial.user then testimonial.user.username  else "Patient" end %>,
                <%= time_ago_in_words(testimonial.created_at)%> ago</small>
          </div>
        </div>
        <% if logged_in? && (current_user == testimonial.user || current_user.admin?) %>
        <div class="testimonial-actions">
        <%= link_to "Edit", edit_testimonial_path(testimonial), class: "btn btn-xs btn-primary" %>
        <%= link_to "Delete", testimonial_path(testimonial), method: :delete,
        data: { confirm: "Are you sure you want to delete the testimonial?"},
        class: "btn btn-xs btn-danger" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/testimonials/edit.html.erb
<h1>Edit your testimonials</h1>

<%= render 'form' %>

app/views/testimonials/index.html.erb
<h1 align="center">Testimonials</h1>
<div align="center">
<%= will_paginate %>
</div>
<%= render 'testimonial',  obj: @testimonials  %>
<div align="center">
<%= will_paginate %>
</div>

app/views/testimonials/new.html.erb
<h1 align="center" id="newpage">Create a new testimonial </h1>
<br>
<%= render 'form' %>

app/views/testimonials/show.html.erb
<h2 align="center"> <%= @testimonial.title %></h2>
<div class="well col-xs-8 col-xs-offset-2 center description testimonial-body">
  "<%= @testimonial.description %>"
  <div class="testimonial-actions">
    <% if @testimonial.user %>
      <ul class="listing">
        <div class="row center">
          <div class="col-md-4 col-md-offset-4">
            <li><%= link_to gravatar_for(@testimonial.user), user_path(@testimonial.user) %></li>
            <li class="testimonial-title">
            <%= link_to @testimonial.user.username, user_path(@testimonial.user) %>
            </li>
            <li><small>
            <%= pluralize(@testimonial.user.testimonials.count, "testimonial") if @testimonial.user.testimonials %>
            </small></li>
          </div>
        </div>
      </ul>
    <% else %>
    <li class="listing">Patient</li>
    <% end %>
  </div>
  <div class="testimonial-actions">
    <% if logged_in? && (current_user == @testimonial.user || current_user.admin?)%>
      <%= link_to "Edit", edit_testimonial_path(@testimonial), class: " btn btn-xs btn-primary" %>
      <%= link_to "Delete", testimonial_path(@testimonial), method: :delete,
                                          data: { confirm: "Are you sure you want to delete the testimonial?"},
                                          class: " btn btn-xs btn-danger" %>
    <% end %>
    <%= link_to "View all", testimonials_path, class: "btn btn-xs btn-success" %>
  </div>
</div>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

  <div class='row'>
    <div class='col-xs-12'>
      <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label "Full Name" %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :username, class: "form-control", placeholder: "Enter Full Name", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :email %>
        </div>
        <div class="col-sm-8">
          <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :password %>
        </div>
        <div class="col-sm-8">
          <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-5 col-sm-10">
          <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: 'btn btn-primary btn-lg') %>
        </div>
      </div>
      <% end %>
      <div class=" col-xs-offset-5 col-sm-4">
      [<%= link_to "Cancel request", testimonials_path %>]
      </div>
    </div>
  </div>

app/views/users/edit.html.erb
<h1 align="center">Edit your account</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">All Patients</h1>
  <div align="center">
    <%= will_paginate %>
    <% @users.each do |user| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li><%= link_to gravatar_for(user), user_path(user) %></li>
              <li>
                <%= "Admin" if user.admin? %>
              </li>
          <li class="testimonial-title">
            <%= link_to user.username, user_path(user) %>
          </li>
          <li><small><%= pluralize(user.testimonials.count, "testimonial") if user.testimonials %></small></li>
          <% if logged_in? and current_user.admin? %>
            <li><%= link_to "Delete this user", user_path(user), method: :delete,
            data: { confirm: "Are you sure you want to delete the user and all their testimonials?" } %></li>
          <% end %>
        </div>
      </div>
    </ul>
    <% end %>
    <%= will_paginate %>
  </div>

app/views/users/new.html.erb
<h1 align="center">Signup for DawaKhana</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s page</h1>
  <div class="row">
    <div class="col-md-4 col-md-offset-4 center">
      <%= gravatar_for @user, size: 150 %>
    </div>
    <div class="col-md-4 col-md-offset-4 center">
      <%= "Admin" if @user.admin? %>
    </div>
  </div>
<h4 align="center"><%= @user.username %>'s testimonials</h4>
<div class="center">
  <%= will_paginate @user_testimonials %>
</div>
<%= render 'testimonials/testimonial', obj: @user.testimonials %>
<div class="center">
  <%= will_paginate @user_testimonials %>
</div>

app/views/welcome/about.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>About</title>
</head>

<body>

  <h1 align="center">About</h1>
  <div class="well col-xs-8 col-xs-offset-2">
    <div class= "username">
    <h2>Dr. Biswajeet Naidu</h2>
    <div class="testimonial-actions">
      Dr Naidu is a leading spine surgeon from Mumbai with over 30 years of work experience.
    </div>
    <div class="testimonial-actions">
      Contact:<br>  
      Mobile: +91 9820072744 <br>
      Suchi-Roy Clinic, #204<br>
      Center Point<br>
      18<sup>th</sup> Road <br>
      Chembur<br>
      Mumbai-400071
  </div>
  </div>
  </div>
  
</body>
</html>

app/views/welcome/home.html.erb
<div class=" center jumbotron">

  <h1 style="font-family:verdana;">DawaKhana</h1>
  <h3>Better Care and Better Understanding</h3>
  <br><br><br>
  <p><a class="btn btn-primary btn-lg" href="signup" role="button"><font color="white">Sign up</font></a></p>
</div>